<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:be.vlaanderen.bodemenondergrond.data.id.graph:codelijst-sedimentairestructuurtype">
  <xs:simpleType name="be.vlaanderen.bodemenondergrond.data.id.conceptscheme.sedimentairestructuurtype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/be" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/bk" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/bo" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/br" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/bt" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ca" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/cb" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/co" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/cu" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ep" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ev" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/fb" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/fn" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/fo" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/fs" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/fu" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ge" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/go" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/gp" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/gt" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/hg" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ik" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ka" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ke" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/kk" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/kl" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ko" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/kr" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/kv" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/la" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/le" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/lf" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/li" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/lm" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/lo" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ma" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/mi" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/mu" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/no" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ob" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/on" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/oo" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/pe" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/pi" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/pl" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ps" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/pt" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/re" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/ru" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/sg" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/sl" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/sp" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/sr" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/st" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/tu" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/us" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/vb" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/vk" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/vs" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/wa" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/zk" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/sedimentairestructuurtype/zw" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
